name: publish
on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
    tags:
      - '*'

jobs:
  skills-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write # for pushing to GHCR
      id-token: write # for signing with cosign
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Install flux
        uses: controlplaneio-fluxcd/flux-operator/actions/setup@b3b36020aca1f8d2172c76949c0bcb6bbf688dde # v0.58.1
      - name: Install cosign
        uses: sigstore/cosign-installer@6f9f17788090df1f26f669e9d70d6ae9567deba6 # v4.1.2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@dbcb813823bdd20940b903addbd779551569679f # v4.6.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Prepare tags
        id: prep
        run: |
          TAG=${{ github.ref_name }}
          VERSION="${{ github.ref_name }}-${GITHUB_SHA::8}"
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            TAG=latest
            VERSION="${{ github.ref_name }}"
          fi
          echo "tag=${TAG}" >> $GITHUB_OUTPUT
          echo "version=${VERSION}" >> $GITHUB_OUTPUT
      - name: Publish skills
        run: |
          flux-operator skills publish ghcr.io/${{ github.repository }} \
            --tag ${{ steps.prep.outputs.version }} \
            --tag ${{ steps.prep.outputs.tag }} \
            --diff-tag ${{ steps.prep.outputs.tag }} \
            -a 'org.opencontainers.image.description=AI Agent Skills for Flux CD' \
            -a 'org.opencontainers.image.licenses=Apache-2.0' \
            --sign
